name: Igress

on:
  push:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: export PATH=$PATH:/home/ubuntu/.nvm/versions/node/v18.14.2/bin
    - run: npm ci
    - run: cp ~/igress/.env ~/actions-runner/_work/igress/igress/.env
    - run: pm2 restart igress
